services:
  wisharr:
    image: vnguyen42/wisharr:latest
    container_name: wisharr
    restart: unless-stopped
    environment:
      - PLEX_TOKEN=${PLEX_TOKEN}
      - OVERSEERR_API_KEY=${OVERSEERR_API_KEY}
      - LOG_LEVEL=info
    volumes:
      - ./config:/app/config
      - ./data:/app/data
